import Head from 'next/head'
import InfluencerSlider from "../components/influencer"
import card1 from "../public/Card_1.svg"
import Image from "next/image"
import styles from '../styles/Home.module.css'
import Navbar from "../components/navbar"
import Footer from '../components/footer'
import audio from "../public/audio.svg"
import summarry from "../public/summary.svg"
import download from "../public/download.svg"
import Hero from '../components/hero'
import InfluencerSliderleft from '../components/infuslide'
import InfluencerSliderright from '../components/infuslideright'

import Influencer from "../pages/new"
export default function Home() {
  return (
    <div>
      <Head>
        <title>Ideopedia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <div className='bg-white'>
        <div className='islider'>
          <span><i>An invitation-only platform that shares cutting-edge ideas</i></span>
          <br />
          <br />
          <span className='str2'>With the top 5000 influencers in India.</span>
        </div>

        <div class="p-6 bg-white-300">


          <div class="grid grid-cols-3 md:grid-cols-3 lg:grid-cols-3 gap-1 lg:gap-1">
            <div class=" rounded-md flex items-center justify-center"><InfluencerSliderleft className="slide" /></div>
            <div class="  rounded-md flex items-center justify-center"><InfluencerSlider className="slide" /></div>
            <div class="  rounded-md flex items-center justify-center"><InfluencerSliderright className="slide" /></div>


          </div>
        </div>
        <br />
        <br />
      </div>
      <div>
        <div id="feat">
          <span >Features</span>
        </div>

        <div class="p-6 bg-white-300">


          <div class="grid grid-cols-1 md:grid-cols-1 lg:grid-cols-3 gap-4 lg:gap-8">
            <div class=" rounded-md flex items-center justify-center"><Image src={card1} /></div>
            <div class="p-4  rounded-md flex items-center justify-center"><Image src={card1} /></div>
            <div class="p-4  rounded-md flex items-center justify-center"><Image src={card1} /></div>
            <div class="p-4  rounded-md flex items-center justify-center"><Image src={card1} /></div>
            <div class="p-4  rounded-md flex items-center justify-center"><Image src={card1} /></div>
            <div class="p-4  rounded-md flex items-center justify-center"><Image src={card1} /></div>

          </div>
        </div>
      </div>
      <div className='bg-white'>
        <div className="container px-6 py-4 mx-auto lg:flex lg:h-128 lg:py-16 ">
          <div className="flex flex-col items-center w-full lg:flex-row lg:w-1/2">
            <Image src={audio} />
          </div>
          <div className="flex items-center justify-center w-full mt-2 lg:h-96 lg:w-1/2">


            <div className="max-w-lg">
              <h1 className="text-xl tracking-wide text-green-800 text-gray-800 lg:text-xl lg:text-2xl">Available in audio & text formats.</h1>
              <p className="mt-4 text-gray-300 text-gray-600">Enjoy access to bestselling book summaries and content from our partners, all available in audio or text segments.</p>
              <div className="mt-6">

              </div>
            </div>


          </div>
        </div>
      </div>
      <div className='bg-white'>
        <div className="container px-6 py-4 mx-auto lg:flex lg:h-128 lg:py-16 ">
          <div className="flex flex-col items-center w-full lg:flex-row lg:w-1/2">
            <div className="max-w-lg">
              <h1 className="text-xl tracking-wide text-green-800 text-gray-800 lg:text-xl lg:text-2xl">Available in audio & text formats.</h1>
              <p className="mt-4 text-gray-300 text-gray-600">Enjoy access to bestselling book summaries and content from our partners, all available in audio or text segments.</p>
              <div className="mt-6">
                <a
                  className=" ">
                  <Image src={download} width={400} />
                </a>
              </div>
            </div>
          </div>
          <div className="flex items-center justify-center w-full mt-2 lg:h-96 lg:w-1/2">

            <Image src={summarry} />


          </div>
        </div>
      </div>
      <br />
      
      <Footer />
    </div>
  )
}
